#!/bin/bash
FILE=md_kernel
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 -s ./$FILE /cfg/md_kernel.config
fi