#!/bin/bash
FILE=md_file_system
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE /cfg/md_file_system.config /cfg/superbloque.dat /cfg/bitmap.dat /cfg/bloques.dat
fi